Features projects page
AlexTRH/cv-Terehov-Shylko pull request #25
Opened 2023-10-09 05:32 UTC by nastassia2020

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/dialogs/projects/projects-form.tsx
> +import { getCreateProjectMutation, getProjectsQuery } from '../../../graphql/projects/projects.queries'
Сейчас поздно уже. На будущее лучше настраивать alias и избегать import '../../' если файл надо будет в ходе рефактора перенести все пути импорта нужно будет менять

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/dialogs/projects/projects-form.tsx
> +export default CreateProjectForm
Линтер и преттиер настроен?

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +  const [DeleteProject] = useMutation<{ affected: number }>(getDeleteProjectMutation, {
Не вижу обработки ошибок, если мутация повалиться

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +  const handleDelete = async () => {
Нужен ли тутasync await? Не вижу лоадера, либо каких то других действий после завершения DeleteProject

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/organisms/projects-table-tool/projects-table-tool.organism.tsx
> +  const CreateClick = () => {
naming wrong. CreateClick с большой буквы? closeForm с маленькой

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/organisms/projects-table-tool/projects-table-tool.organism.tsx
> +  const create = async () => {
async. Do we need it here?

2023-10-12 11:35 UTC, dzianislysionak commented on src/components/organisms/skills-table-tool/skills-table-tool.organism.tsx
> +
Пустая строка мне кажется - это случайность

2023-10-12 11:35 UTC, dzianislysionak commented on src/pages/projects/projects-page.tsx
> +  const { data, loading, error } = useQuery<ProjectsResult>(getProjectsQuery)
Не вижу, где error используется

2023-10-12 15:03 UTC, nastassia2020 commented on src/components/dialogs/projects/projects-form.tsx
> +import { getCreateProjectMutation, getProjectsQuery } from '../../../graphql/projects/projects.queries'
ок, я поняла

2023-10-12 15:08 UTC, nastassia2020 commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +  const handleDelete = async () => {
ну да, получается, что async await тут лишние

2023-10-12 15:11 UTC, nastassia2020 commented on src/components/organisms/projects-table-tool/projects-table-tool.organism.tsx
> +  const create = async () => {
no, we don't

2023-10-17 06:01 UTC, nastassia2020 commented on src/components/organisms/skills-table-tool/skills-table-tool.organism.tsx
> +
какую пустую строку ты имеешь ввиду?

2023-10-17 06:08 UTC, nastassia2020 commented on src/pages/projects/projects-page.tsx
> +  const { data, loading, error } = useQuery<ProjectsResult>(getProjectsQuery)
добавила в preloader

2023-10-17 06:10 UTC, nastassia2020 commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +  const [DeleteProject] = useMutation<{ affected: number }>(getDeleteProjectMutation, {
создала preloader и теперь обрабатываю ошибки на главной странице ProjectsPage

2023-10-17 06:49 UTC, dzianislysionak requested changes

2023-10-17 06:49 UTC, dzianislysionak commented on src/components/organisms/skills-table-tool/skills-table-tool.organism.tsx
> +
То что плюс на зеленом фоне
![image](https://github.com/AlexTRH/cv-Terehov-Shylko/assets/59472058/eaf48716-45bc-4309-84fd-9afce1ea2c8c)

2023-10-17 06:49 UTC, dzianislysionak commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +  const [DeleteProject] = useMutation<{ affected: number }>(getDeleteProjectMutation, {
Добавить error

2023-10-18 06:30 UTC, nastassia2020 commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +  const [DeleteProject] = useMutation<{ affected: number }>(getDeleteProjectMutation, {
добавила onError, пока выводит в консоль

2023-10-18 06:40 UTC, dzianislysionak requested changes
Поделись плиз с Лешей нашей вчерашней беседой, все комменты должны быть с ответной реакцией. Тут ничего не было с твоей стороны
![image](https://github.com/AlexTRH/cv-Terehov-Shylko/assets/59472058/83f5b0a3-d967-4bdd-8aaa-8d6cef033738)

2023-10-18 06:40 UTC, dzianislysionak commented on src/components/organisms/projects-table-row/projects-table-row.organism.tsx
> +      console.error('An error occurred during the mutation:', error)
Console - не приемлемо. Для юзера это вообще не информативно. Согласуйте с Лешей, что будете использовать и сделать нормальную реализацию. Всегда думайте со стороны пользователя, который не знает, что вообще консоль существует

2023-10-18 06:40 UTC, dzianislysionak commented on src/components/organisms/skills-table-tool/skills-table-tool.organism.tsx
> +
Удали плиз строку которая была добавлена

2023-10-18 13:52 UTC, nastassia2020 commented on src/components/organisms/skills-table-tool/skills-table-tool.organism.tsx
> +
done, надеюсь я правильно поняла)

2023-10-19 08:45 UTC, merged