created employee cvs page
AlexTRH/cv-Terehov-Shylko pull request #27
Opened 2023-10-19 09:34 UTC by AlexTRH

2023-10-19 11:05 UTC, dzianislysionak requested changes

2023-10-19 11:05 UTC, dzianislysionak commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +  const { data, loading } = useQuery<UserResult>(getUserCVsQuery, {
Поговори с Настей. Она реализовала Preloader с обработкой ошибок. Если по функуионалу подойдет необходимо заюзать, если нет, сделать реюзабл компонент для Loading + Во всех запросах необходимо обрабатывать ошибки. Если запрос валится юзер должен видеть это

2023-10-20 09:47 UTC, AlexTRH commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +  const { data, loading } = useQuery<UserResult>(getUserCVsQuery, {
Done

2023-10-20 10:21 UTC, dzianislysionak approved these changes
Все норм. Единственное ты частично заюзал алиасы. Давай во всем ПР добавь их и можешь мержить
![image](https://github.com/AlexTRH/cv-Terehov-Shylko/assets/59472058/5703cc6d-4d0d-49ed-9553-5f096bbcfe9c)

2023-10-20 11:56 UTC, AlexTRH commented
> Все норм. Единственное ты частично заюзал алиасы. Давай во всем ПР добавь их и можешь мержить ![image](https://user-images.githubusercontent.com/59472058/276901356-5703cc6d-4d0d-49ed-9553-5f096bbcfe9c.png)

Done

2023-10-20 12:51 UTC, bobrishyova commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +        {cvs.length === 0 ? (
вынеси в if если !cvs.length

2023-10-23 07:53 UTC, AlexTRH commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +        {cvs.length === 0 ? (
Done

2023-10-23 07:54 UTC, merged