Features cvs page
AlexTRH/cv-Terehov-Shylko pull request #29
Opened 2023-10-23 06:41 UTC by nastassia2020

2023-10-23 06:59 UTC, dzianislysionak requested changes

2023-10-23 06:59 UTC, dzianislysionak commented on src/components/dialogs/cvs/CreateCvForm.tsx
> +  const [createCV, { loading }] = useMutation(createCv, {
errorHandeling пропущен. Должен быть для всех запросов. Используем ли мы loading?

2023-10-23 06:59 UTC, dzianislysionak commented on src/components/dialogs/language/language.tsx
> +const Language = ({ item, closeDialog }: LanguageProps) => {
Давай переименуем item - для меня не понятно, что такое item

2023-10-23 06:59 UTC, dzianislysionak commented on src/components/dialogs/language/language.tsx
> +      updateLanguage({
errorHandeling

2023-10-23 06:59 UTC, dzianislysionak commented on src/components/dialogs/language/language.tsx
> +      createLanguage({
errorHandeling

2023-10-23 06:59 UTC, dzianislysionak commented on src/components/organisms/cvs-table-row/cvs-table-row.organism.tsx
> +export const CVsTableRow = ({ item }: TableRowProps<ICV>) => {
reminder - item  is a bad name

2023-10-23 06:59 UTC, dzianislysionak commented on src/components/organisms/languages-table-row/languages-table-row.tsx
> +        {t('Are you sure you want to delete language')} <b>{item.name}</b>?
Давай созвонимся, хочу больше знать, как вы пользуетесь useTranslation. Обычно используются ключи. "Are you sure you want to delete language" выглядит не правильно для меня

2023-10-23 06:59 UTC, dzianislysionak commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +  if (!data || loading) {
Можем ли мы использовать Preloader + error. Если нет - объясни плиз

2023-10-23 06:59 UTC, dzianislysionak commented on src/pages/employee-skills/employee-skills.page.tsx
> +  if (loading || !data) {
То же самое Preloader + error

2023-10-23 09:31 UTC, bobrishyova commented on src/components/dialogs/cvs/CreateCvForm.tsx
> +    <>
зачем тут фрагмент?

2023-10-23 09:31 UTC, bobrishyova commented on src/components/dialogs/cvs/FormFields.tsx
> +interface Props {
договаривались, что interface выносим в отдельный файл в той же папке

2023-10-23 10:52 UTC, nastassia2020 commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +  if (!data || loading) {
Это страничка Лёши)

2023-10-23 10:53 UTC, nastassia2020 commented on src/pages/employee-skills/employee-skills.page.tsx
> +  if (loading || !data) {
и это для Лёши

2023-10-23 10:54 UTC, nastassia2020 commented on src/components/dialogs/cvs/CreateCvForm.tsx
> +    <>
уже нет его, обернула в Preloader

2023-10-23 10:55 UTC, nastassia2020 commented on src/components/dialogs/cvs/CreateCvForm.tsx
> +  const [createCV, { loading }] = useMutation(createCv, {
сделано, loading использую в Preloader сейчас

2023-10-23 10:56 UTC, nastassia2020 commented on src/components/dialogs/language/language.tsx
> +const Language = ({ item, closeDialog }: LanguageProps) => {
done

2023-10-23 10:56 UTC, nastassia2020 commented on src/components/dialogs/language/language.tsx
> +      updateLanguage({
done

2023-10-23 10:56 UTC, nastassia2020 commented on src/components/dialogs/language/language.tsx
> +      createLanguage({
done

2023-10-23 10:56 UTC, nastassia2020 commented on src/components/organisms/cvs-table-row/cvs-table-row.organism.tsx
> +export const CVsTableRow = ({ item }: TableRowProps<ICV>) => {
done

2023-10-23 10:58 UTC, nastassia2020 commented on src/components/organisms/languages-table-row/languages-table-row.tsx
> +        {t('Are you sure you want to delete language')} <b>{item.name}</b>?
у нас ключи и используются из словаря в public/translations. Но если нужно, созвонимся завтра утром

2023-10-23 11:16 UTC, nastassia2020 commented on src/components/dialogs/cvs/FormFields.tsx
> +interface Props {
sorry, done

2023-10-24 09:46 UTC, AlexTRH commented on src/pages/employee-cvs/employee-cvs.page.tsx
> +  if (!data || loading) {
Да, ты оставлял этот коммент мне. Я добавил Preloader + error

2023-10-24 09:51 UTC, AlexTRH commented on src/pages/employee-skills/employee-skills.page.tsx
> +  if (loading || !data) {
Добавил Preloader

2023-10-24 13:36 UTC, merged